name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    run-on: ubuntu-latest
    stepms:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Say jello
        run: echo Hello
